name = "chicken-road-gameapp-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chicken-road-gameapp.com"
HMAC_KEY = "7cc2d0dfe281a40855d83212514e6694f302745c7b8dc9fa5ef7b62666a74438"
COOKIE_NAME = "9rz"
PLAY_PATH = "try"
BUTTON_ID = "pb8bf8e2cbe436641e016d3a0e401df5b"
GATE_SALT = "009c2f48b9d3d8ec"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "3md4"
CTA_SELECTOR = ".play-button"
